.TH "_PRINTF" 3 GNU "_printf Manual"
.SH NAME
_printf \- formatted output conversion
.SH SYNOPSIS
.B # include "main.h"
.br
.sp
.B int _printf(const char *\fPformat\fB, ...);
.SH DESCRIPTION
.SH AUTHORS
.B Haffie023
.B gekkowrld

// why is this important? It's not
// ooh hahaha. okay. carry on
// this is our "man page" for our unfinished project
// trying to think on what to write 
// does it have to be technical?
// mostly but not oftenly
// " a project to come up and call our own functions based on the _printf tasks on ALX."
// Then copy the tasks as given. 
// then end it with, " a collaboration between "gekkoworld amd Haffie023" or whatever github names 
// you are comfortable using
// will definately consider this, but we should now focus on the 
// important ones before time runs out
// you are right. was a good commercial break 
